kind: Service
apiVersion: v1
metadata:
  name: autodqm
  namespace: dqm
spec:
  selector:
    app: autodqm
  ports:
    - port: 8083
      targetPort: 8083
      name: autodqm
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: autodqm
  name: autodqm
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: autodqm
  replicas: 1
  template:
    metadata:
      labels:
        app: autodqm
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18083"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - image: registry.cern.ch/cmsweb/autodqm #imagetag
        name: autodqm
        env:
         - name: HOME
           value: /
        resources:
          requests:
            memory: "500Mi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "4000m"
        ports:
        - containerPort: 8083
          protocol: TCP
          name: autodqm
        - containerPort: 18083
          protocol: TCP
          name: dqmwebapp-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: robot-secrets
          mountPath: /etc/robots
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets          
