kind: Service
apiVersion: v1
metadata:
  name: das-mongo
  namespace: das
spec:
  selector:
    app: das-mongo
  ports:
    - port: 8230
      targetPort: 8230
      name: das
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: das-mongo
  name: das-mongo
  namespace: das
spec:
  selector:
    matchLabels:
      app: das-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: das-mongo
        env: k8s #k8s#
# should be enabled once we'll have exporter running with this sercice
# we should also add prometheus.io/port in that case
#       annotations:
#         prometheus.io/scrape: 'true'
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: registry.cern.ch/cmsweb/das-mongo #imagetag
        name: das-mongo
        tty: true
        stdin: true
        resources:
          requests:
            memory: "3000Mi"
            cpu: "2000m"
          limits:
            memory: "6Gi"
            cpu: "4000m"
        ports:
        - containerPort: 8230
          protocol: TCP
          name: das
        - containerPort: 18230
          protocol: TCP
          name: das-mongo-mon
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: das-mongo-secrets
