kind: Service
apiVersion: v1
metadata:
  name: dmwmmon
  namespace: dmwm
spec:
  selector:
    app: dmwmmon
  ports:
    - port: 8280
      targetPort: 8280
      name: dmwmmon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dmwmmon
  labels:
    app: dmwmmon
  namespace: dmwm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _dmwmmon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dmwmmon
  name: dmwmmon
  namespace: dmwm
spec:
  selector:
    matchLabels:
      app: dmwmmon
  replicas: 1
  template:
    metadata:
      labels:
        app: dmwmmon
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/dmwmmon #imagetag
        name: dmwmmon
        ports:
        - containerPort: 8280
          protocol: TCP
          name: dmwmmon
        - containerPort: 18280
          protocol: TCP
          name: dmwmmon-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
#       - name: secrets
#         mountPath: /etc/secrets
#          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run

        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
#     - name: secrets
#        secret:
#         secretName: dmwmmon-secrets
          # https://github.com/kubernetes/kubernetes/issues/34982
#         readOnly: true
#         items:
#           - key: "robotcert.pem"
#             path: "robotcert.pem"
#             mode: 0640
#           - key: "robotkey.pem"
#             path: "robotkey.pem"
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dmwmmon

