kind: Service
apiVersion: v1
metadata:
  name: dqmgui
  namespace: dqm
spec:
  selector:
    app: dqmgui
  ports:
    - port: 8060
      targetPort: 8060
      name: dqmgui-dev
    - port: 8081
      targetPort: 8081
      name: dqmgui-relval
    - port: 8080
      targetPort: 8080
      name: dqmgui-offline
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dqmgui
  labels:
    app: dqmgui
  namespace: dqm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    su  -c "cd /data && /data/run.sh" --preserve-environment _dqmgui
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dqmgui
  name: dqmgui
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: dqmgui
  replicas: 1   
  template:
    metadata:
      labels:
        app: dqmgui
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: cmssw/dqmgui #imagetag
        name: dqmgui
        tty: true
        stdin: true
#         lifecycle:
#           postStart:
#             exec:
#               command:
#               - bash
#               - -c
#               - sudo chmod 0777 /data/srv/state/dqmgui/data; sudo chown _dqmgui:_dqmgui /data/srv/state/dqmgui/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8060
          protocol: TCP
          name: dqmgui-dev
        - containerPort: 8081
          protocol: TCP
          name: dqmgui-relval
        - containerPort: 8080
          protocol: TCP
          name: dqmgui-offline
        - containerPort: 18060
          protocol: TCP
          name: dqmgui-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run

        securityContext:
          privileged: true
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dqmgui-secrets
      - name: etc-grid-security
        hostPath:
          path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: dqmgui

