kind: Deployment
apiVersion: apps/v1
metadata:
  name: filebeat
  namespace: auth
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: store/elastic/filebeat:7.9.2
        args: [
          "-c", "/etc/secrets/filebeat.yml",
          "-e",
        ]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true

      - name: data
        hostPath:
          # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: secrets
        secret:
          secretName: filebeat-secrets
