kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
# VK: use this section if we'll deploy OAuth and leave machine tools to go
# through frontend on port 8843
#   type: NodePort
#   ports:
#     - port: 8443
#       targetPort: 8443
#       name: https-machine
#     - port: 18443
#       targetPort: 18443
#       name: http-mon
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 8443
      name: https
    - port: 8443
      targetPort: 8443
      name: https-machine
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2   
  template:
    metadata:
      labels:
        app: frontend
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18443"
    spec:
      containers:
      - image: registry.cern.ch/cmsweb/frontend #imagetag
        name: frontend
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "6Gi"
            cpu: "4000m"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        - containerPort: 8443
          protocol: TCP
          name: https-machine
        - containerPort: 18443
          protocol: TCP
          name: http-mon

        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: hmac-secrets
          mountPath: /etc/hmac
          readOnly: true
# We use explicit path declaration for certificates in FE because we need certificates directory in /etc/grid-security/ which is not created without explicit declaration
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem

      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: frontend-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
