kind: Service
apiVersion: v1
metadata:
  name: ms-output-mongo
  namespace: dmwm
spec:
  selector:
    app: ms-output-mongo
  ports:
    - port: 8230
      targetPort: 8230
      name: ms-output-mongo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ms-output-mongo
  name: ms-output-mongo
  namespace: dmwm
spec:
  selector:
    matchLabels:
      app: ms-output-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-output-mongo
        env: k8s #k8s#
# should be enabled once we'll have exporter running with this sercice
# we should also add prometheus.io/port in that case
#       annotations:
#         prometheus.io/scrape: 'true'
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: registry.cern.ch/cmsweb/ms-output-mongo #imagetag
        name: ms-output-mongo
        tty: true
        stdin: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "5Gi"
            cpu: "4000m"
        ports:
        - containerPort: 8230
          protocol: TCP
          name: ms-output-mongo
        - containerPort: 18230
          protocol: TCP
          name: ms-output-mon
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true

      volumes:
      - name: secrets
        secret:
          secretName: ms-output-mongo-secrets
