apiVersion: v1
kind: ServiceAccount
metadata:
  name: podmanager-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podmanager
subjects:
- kind: ServiceAccount
  name: podmanager-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: podmanager
  name: podmanager
spec:
  selector:
    matchLabels:
      app: podmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: podmanager
    spec:
      serviceAccountName: podmanager-sa
      containers:
      - image: registry.cern.ch/cmsweb/podmanager #imagetag
        name: podmanager
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        command:
        - /data/PodManager
        - -config
        - /etc/secrets/config.json
        volumeMounts:
        - name: podmanager-secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: podmanager-secrets
        secret:
          secretName: podmanager-secrets
