kind: Service
apiVersion: v1
metadata:
  name: quota-exporter
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 18000
    protocol: TCP
    name: http
  selector:
    app: quota-exporter
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: quota-exporter
  name: quota-exporter
  namespace: http
spec:
  selector:
    matchLabels:
      app: quota-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: quota-exporter
    spec:
      containers:
      - image: registry.cern.ch/cmsweb/quota-exporter #imagetag
        args:
        - /data/quota_exporter
        - -script
        - /data/quota.sh
        - -env
        - /etc/secrets/keystone_env.sh
        - -namespace
        - "openstack"
        - -address
        - ":18000"
        - -endpoint
        - "/metrics"
        name: quota-exporter
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ls"]
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: quota-exporter-secrets
