kind: Service
apiVersion: v1
metadata:
  name: registry-notification
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 9215 # the port here is matching port used in registry.cern.ch/cmsweb/registry-notification cotainer
    protocol: TCP
    name: http
  selector:
    app: registry-notification
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: registry-notification
  name: registry-notification
  namespace: http
spec:
  selector:
    matchLabels:
      app: registry-notification
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-notification
    spec:
      containers:
      - image: registry.cern.ch/cmsweb/registry-notification #imagetag
        name: registry-notification
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9215
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        # here is an example how to run post command
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ls"]
        ports:
        - containerPort: 9215
